### ISSUE TITLE
How to get tooltip for line chart

### ISSUE THREAD

**Issue by SagarPrakash01** [datencia/d3js-angular-examples#18]
How to get tool tip for line chart showing current x and y axis parameters

**Comment by datencia** [comment]
Hi, sorry for the long time. I've been off.

You can find an example here [Line Chart with Tooltip 1](https://bl.ocks.org/Qizly/8f6ba236b79d9bb03a80) in vanilla javascript.

**Comment by Arjun-Shinojiya** [comment]
@SagarPrakash01 Have you solved the tooltip issue?
