### ISSUE TITLE
Showing Error at the time of compilation

### ISSUE THREAD

**Issue by parthchat99** [datencia/d3js-angular-examples#21]
I am getting this type of error.

Error: attribute height: A negative value is not valid. ("-3")
(anonymous) @ attr.js:31
(anonymous) @ each.js:5
(anonymous) @ attr.js:53
push../src/app/content/pages/components/dashboard/opportunities-lead-source/opportunities-lead-source.component.ts.OpportunitiesLeadSourceComponent.drawChart @ opportunities-lead-source.component.ts:91
push../src/app/content/pages/components/dashboard/opportunities-lead-source/opportunities-lead-source.component.ts.OpportunitiesLeadSourceComponent.ngOnInit @ opportunities-lead-source.component.ts:44
checkAndUpdateDirectiveInline @ core.js:9243
checkAndUpdateNodeInline @ core.js:10507
checkAndUpdateNode @ core.js:10469
debugCheckAndUpdateNode @ core.js:11102
debugCheckDirectivesFn @ core.js:11062
(anonymous) @ OpportunitiesLeadSourceComponent_Host.ngfactory.js? [sm]:1
debugUpdateDirectives @ core.js:11054
checkAndUpdateView @ core.js:10451
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execComponentViewsAction @ core.js:10634
checkAndUpdateView @ core.js:10457
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execComponentViewsAction @ core.js:10634
checkAndUpdateView @ core.js:10457
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execComponentViewsAction @ core.js:10634
checkAndUpdateView @ core.js:10457
callWithDebugContext @ core.js:11344
debugCheckAndUpdateView @ core.js:11022
push../node_modules/@angular/core/fesm5/core.js.ViewRef_.detectChanges @ core.js:8838
(anonymous) @ core.js:4571
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick @ core.js:4571
(anonymous) @ core.js:4462
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:3820
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.run @ core.js:3734
next @ core.js:4462
schedulerFn @ core.js:3551
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:196
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:134
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:3535
checkStable @ core.js:3789
onHasTask @ core.js:3833
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.hasTask @ zone.js:441
push../node_modules/zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ zone.js:461
push../node_modules/zone.js/dist/zone.js.Zone.updateTaskCount @ zone.js:285
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:595
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
attr.js:31 Error: attribute height: A negative value is not valid. ("-6")
(anonymous) @ attr.js:31
(anonymous) @ each.js:5
(anonymous) @ attr.js:53
push../src/app/content/pages/components/dashboard/opportunities-lead-source/opportunities-lead-source.component.ts.OpportunitiesLeadSourceComponent.drawChart @ opportunities-lead-source.component.ts:91
push../src/app/content/pages/components/dashboard/opportunities-lead-source/opportunities-lead-source.component.ts.OpportunitiesLeadSourceComponent.ngOnInit @ opportunities-lead-source.component.ts:44
checkAndUpdateDirectiveInline @ core.js:9243
checkAndUpdateNodeInline @ core.js:10507
checkAndUpdateNode @ core.js:10469
debugCheckAndUpdateNode @ core.js:11102
debugCheckDirectivesFn @ core.js:11062
(anonymous) @ OpportunitiesLeadSourceComponent_Host.ngfactory.js? [sm]:1
debugUpdateDirectives @ core.js:11054
checkAndUpdateView @ core.js:10451
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execComponentViewsAction @ core.js:10634
checkAndUpdateView @ core.js:10457
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execComponentViewsAction @ core.js:10634
checkAndUpdateView @ core.js:10457
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execComponentViewsAction @ core.js:10634
checkAndUpdateView @ core.js:10457
callWithDebugContext @ core.js:11344
debugCheckAndUpdateView @ core.js:11022
push../node_modules/@angular/core/fesm5/core.js.ViewRef.detectChanges @ core.js:8838
(anonymous) @ core.js:4571
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick @ core.js:4571
(anonymous) @ core.js:4462
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:3820
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.run @ core.js:3734
next @ core.js:4462
schedulerFn @ core.js:3551
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:196
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:134
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:3535
checkStable @ core.js:3789
onHasTask @ core.js:3833
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.hasTask @ zone.js:441
push../node_modules/zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ zone.js:461
push../node_modules/zone.js/dist/zone.js.Zone.updateTaskCount @ zone.js:285
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:595
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
attr.js:31 Error: attribute height: A negative value is not valid. ("-2")
(anonymous) @ attr.js:31
(anonymous) @ each.js:5
(anonymous) @ attr.js:53
push../src/app/content/pages/components/dashboard/opportunities-lead-source/opportunities-lead-source.component.ts.OpportunitiesLeadSourceComponent.drawChart @ opportunities-lead-source.component.ts:91
push../src/app/content/pages/components/dashboard/opportunities-lead-source/opportunities-lead-source.component.ts.OpportunitiesLeadSourceComponent.ngOnInit @ opportunities-lead-source.component.ts:44
checkAndUpdateDirectiveInline @ core.js:9243
checkAndUpdateNodeInline @ core.js:10507
checkAndUpdateNode @ core.js:10469
debugCheckAndUpdateNode @ core.js:11102
debugCheckDirectivesFn @ core.js:11062
(anonymous) @ OpportunitiesLeadSourceComponent_Host.ngfactory.js? [sm]:1
debugUpdateDirectives @ core.js:11054
checkAndUpdateView @ core.js:10451
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execComponentViewsAction @ core.js:10634
checkAndUpdateView @ core.js:10457
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execComponentViewsAction @ core.js:10634
checkAndUpdateView @ core.js:10457
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execComponentViewsAction @ core.js:10634
checkAndUpdateView @ core.js:10457
callWithDebugContext @ core.js:11344
debugCheckAndUpdateView @ core.js:11022
push../node_modules/@angular/core/fesm5/core.js.ViewRef.detectChanges @ core.js:8838
(anonymous) @ core.js:4571
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick @ core.js:4571
(anonymous) @ core.js:4462
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:3820
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.run @ core.js:3734
next @ core.js:4462
schedulerFn @ core.js:3551
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:196
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:134
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:3535
checkStable @ core.js:3789
onHasTask @ core.js:3833
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.hasTask @ zone.js:441
push../node_modules/zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ zone.js:461
push../node_modules/zone.js/dist/zone.js.Zone.updateTaskCount @ zone.js:285
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:595
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
attr.js:31 Error: attribute height: A negative value is not valid. ("-5")
(anonymous) @ attr.js:31
(anonymous) @ each.js:5
(anonymous) @ attr.js:53
push../src/app/content/pages/components/dashboard/opportunities-lead-source/opportunities-lead-source.component.ts.OpportunitiesLeadSourceComponent.drawChart @ opportunities-lead-source.component.ts:91
push../src/app/content/pages/components/dashboard/opportunities-lead-source/opportunities-lead-source.component.ts.OpportunitiesLeadSourceComponent.ngOnInit @ opportunities-lead-source.component.ts:44
checkAndUpdateDirectiveInline @ core.js:9243
checkAndUpdateNodeInline @ core.js:10507
checkAndUpdateNode @ core.js:10469
debugCheckAndUpdateNode @ core.js:11102
debugCheckDirectivesFn @ core.js:11062
(anonymous) @ OpportunitiesLeadSourceComponent_Host.ngfactory.js? [sm]:1
debugUpdateDirectives @ core.js:11054
checkAndUpdateView @ core.js:10451
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execComponentViewsAction @ core.js:10634
checkAndUpdateView @ core.js:10457
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execComponentViewsAction @ core.js:10634
checkAndUpdateView @ core.js:10457
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execComponentViewsAction @ core.js:10634
checkAndUpdateView @ core.js:10457
callWithDebugContext @ core.js:11344
debugCheckAndUpdateView @ core.js:11022
push../node_modules/@angular/core/fesm5/core.js.ViewRef.detectChanges @ core.js:8838
(anonymous) @ core.js:4571
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick @ core.js:4571
(anonymous) @ core.js:4462
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:3820
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.run @ core.js:3734
next @ core.js:4462
schedulerFn @ core.js:3551
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:196
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:134
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:3535
checkStable @ core.js:3789
onHasTask @ core.js:3833
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.hasTask @ zone.js:441
push../node_modules/zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ zone.js:461
push../node_modules/zone.js/dist/zone.js.Zone.updateTaskCount @ zone.js:285
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:595
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
2attr.js:31 Error: attribute height: A negative value is not valid. ("-12")
(anonymous) @ attr.js:31
(anonymous) @ each.js:5
(anonymous) @ attr.js:53
push../src/app/content/pages/components/dashboard/opportunities-lead-source/opportunities-lead-source.component.ts.OpportunitiesLeadSourceComponent.drawChart @ opportunities-lead-source.component.ts:91
push../src/app/content/pages/components/dashboard/opportunities-lead-source/opportunities-lead-source.component.ts.OpportunitiesLeadSourceComponent.ngOnInit @ opportunities-lead-source.component.ts:44
checkAndUpdateDirectiveInline @ core.js:9243
checkAndUpdateNodeInline @ core.js:10507
checkAndUpdateNode @ core.js:10469
debugCheckAndUpdateNode @ core.js:11102
debugCheckDirectivesFn @ core.js:11062
(anonymous) @ OpportunitiesLeadSourceComponent_Host.ngfactory.js? [sm]:1
debugUpdateDirectives @ core.js:11054
checkAndUpdateView @ core.js:10451
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execComponentViewsAction @ core.js:10634
checkAndUpdateView @ core.js:10457
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execComponentViewsAction @ core.js:10634
checkAndUpdateView @ core.js:10457
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execComponentViewsAction @ core.js:10634
checkAndUpdateView @ core.js:10457
callWithDebugContext @ core.js:11344
debugCheckAndUpdateView @ core.js:11022
push../node_modules/@angular/core/fesm5/core.js.ViewRef.detectChanges @ core.js:8838
(anonymous) @ core.js:4571
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick @ core.js:4571
(anonymous) @ core.js:4462
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:3820
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.run @ core.js:3734
next @ core.js:4462
schedulerFn @ core.js:3551
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:196
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:134
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:3535
checkStable @ core.js:3789
onHasTask @ core.js:3833
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.hasTask @ zone.js:441
push../node_modules/zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ zone.js:461
push../node_modules/zone.js/dist/zone.js.Zone.updateTaskCount @ zone.js:285
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:595
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
attr.js:31 Error: attribute height: A negative value is not valid. ("-7")
(anonymous) @ attr.js:31
(anonymous) @ each.js:5
(anonymous) @ attr.js:53
push../src/app/content/pages/components/dashboard/opportunities-lead-source/opportunities-lead-source.component.ts.OpportunitiesLeadSourceComponent.drawChart @ opportunities-lead-source.component.ts:91
push../src/app/content/pages/components/dashboard/opportunities-lead-source/opportunities-lead-source.component.ts.OpportunitiesLeadSourceComponent.ngOnInit @ opportunities-lead-source.component.ts:44
checkAndUpdateDirectiveInline @ core.js:9243
checkAndUpdateNodeInline @ core.js:10507
checkAndUpdateNode @ core.js:10469
debugCheckAndUpdateNode @ core.js:11102
debugCheckDirectivesFn @ core.js:11062
(anonymous) @ OpportunitiesLeadSourceComponent_Host.ngfactory.js? [sm]:1
debugUpdateDirectives @ core.js:11054
checkAndUpdateView @ core.js:10451
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execComponentViewsAction @ core.js:10634
checkAndUpdateView @ core.js:10457
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execComponentViewsAction @ core.js:10634
checkAndUpdateView @ core.js:10457
callViewAction @ core.js:10692
execEmbeddedViewsAction @ core.js:10655
checkAndUpdateView @ core.js:10452
callViewAction @ core.js:10692
execComponentViewsAction @ core.js:10634
checkAndUpdateView @ core.js:10457
callWithDebugContext @ core.js:11344
debugCheckAndUpdateView @ core.js:11022
push../node_modules/@angular/core/fesm5/core.js.ViewRef.detectChanges @ core.js:8838
(anonymous) @ core.js:4571
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick @ core.js:4571
(anonymous) @ core.js:4462
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:3820
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.run @ core.js:3734
next @ core.js:4462
schedulerFn @ core.js:3551
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:196
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:134
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:3535
checkStable @ core.js:3789
onHasTask @ core.js:3833
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.hasTask @ zone.js:441
push../node_modules/zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ zone.js:461
push../node_modules/zone.js/dist/zone.js.Zone._updateTaskCount @ zone.js:285
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:595
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566

**Comment by parthchat99** [comment]
![screenshot from 2018-12-29 12-41-13](https://user-images.githubusercontent.com/41331578/50534747-4a717f80-0b67-11e9-8b8c-8fb1a3509235.png)

**Comment by datencia** [comment]
Sorry @parthchat99 I've been off. Seems you are calculating a negative value. No idea about your code, try to find it and fix it.
